# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.debug=false

neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.219
neo_version_range=[21.1.0,)
loader_version_range=[4,)
create_version_range=[6.0.4,6.1)

create_version=6.0.10-280
flywheel_version=1.0.6
registrate_version=MC1.21-1.3.0+67
ponder_version=1.0.82
jei_version=19.21.0.247

## Mod Properties
mod_id=lazyengines
mod_name=Create: Lazy Engines
mod_license=MIT
mod_version=2.1.0
mod_group_id=com.natim6.lazyengines
mod_authors=NatiM6
mod_description=Adds config options to Steam Engines
